import type { Layer } from './firebase';
import { stringify } from 'wellknown';

export function generatePostgisSQL(layer: Layer, tableName: string): string {
    const featuresRaw = typeof layer.features === 'string' ? JSON.parse(layer.features) : layer.features;
    const features: any[] = featuresRaw?.features ?? [];

    if (features.length === 0) {
        return `-- Layer "${layer.name}" has no features.\n`;
    }

    // Collect all property keys across all features (excluding internal keys)
    const allKeys = new Set<string>();
    for (const f of features) {
        for (const k of Object.keys(f.properties ?? {})) {
            if (!k.startsWith('_')) allKeys.add(k);
        }
    }
    const propCols = Array.from(allKeys);

    const lines: string[] = [];
    lines.push(`-- Generated by WKT Studio`);
    lines.push(`-- Layer: ${layer.name} (${features.length} feature${features.length !== 1 ? 's' : ''})`);
    lines.push('');
    lines.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);
    lines.push(`    id SERIAL PRIMARY KEY,`);
    for (const col of propCols) {
        lines.push(`    ${sanitizeColName(col)} TEXT,`);
    }
    lines.push(`    geom GEOMETRY(GEOMETRY, 4326)`);
    lines.push(`);`);
    lines.push('');

    const valueRows: string[] = [];
    for (const f of features) {
        let wkt: string | null = null;
        try {
            wkt = stringify(f.geometry);
        } catch {
            wkt = null;
        }
        if (!wkt) continue;

        const propValues = propCols.map(col => {
            const val = f.properties?.[col];
            if (val == null) return 'NULL';
            return `'${String(val).replace(/'/g, "''")}'`;
        });

        const geomExpr = `ST_GeomFromText('${wkt}', 4326)`;
        const allVals = [...propValues, geomExpr].join(', ');
        valueRows.push(`    (${allVals})`);
    }

    if (valueRows.length > 0) {
        const colList = [...propCols.map(sanitizeColName), 'geom'].join(', ');
        lines.push(`INSERT INTO ${tableName} (${colList}) VALUES`);
        lines.push(valueRows.join(',\n') + ';');
    }

    return lines.join('\n');
}

function sanitizeColName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^([0-9])/, '_$1').toLowerCase();
}
